[SENSOR_LIST]
64 = port1 link speed
65 = port2 link speed
66 = port3 link speed
67 = port4 link speed

C8 = port1 link state
C9 = port2 link state
CA = port3 link state
CB = port4 link state

012C = network controller temp
01F4 = port1 transceiver temp
01F5 = port2 transceiver temp
01F6 = port3 transceiver temp
01F7 = port4 transceiver temp

# https://www.dmtf.org/sites/default/files/standards/documents/DSP0249_1.3.0.pdf

[LINK_STATE]
01 = data layer link up
02 = data layer link down

[LEASH_STATUS]
01 = physical layer connected
02 = physical layer disconnected

[HEALTH_STATE]
01 = normal 
02 = non-critical 
03 = critical 
04 = fatal 
05 = upper non-critical 
06 = low non-critical
07 = upper critical
08 = lower critical
09 = upper fatal
10 = lower fatal

[AVAILIABILITY]
01 = enabled 
02 = disable
03 = shutdown
04 = offline
05 = in test
06 = defferred
07 = quiescent
08 = rebooting
09 = resetting
10 = failed
11 = not installed
12 = power save mode
13 = paused
14 = shutting down
15 = starting
16 = not responding

[PREDICTIVE_CONDITION]
01 = normal
02 = predictive failure

[CONFIGURATION_STATE]
01 = valid configuration
02 = invalid configuration
03 = not configured
04 = missing configuration

[CHANGE_CONFIGURATION]
01 = normal
02 = configuration change detected

[VERSION]
01 = normal
02 = version change detected – compatible
03 = version change detected – incompatible
04 = version change pending

[DEVICE_POWER_STATE]
01 = ACPI Device Power State is D0: Fully-On
02 = ACPI Device Power State is D1.Intermediate Power State 1
03 = ACPI Device Power State is D2.Intermediate Power State 2
04 = ACPI Device Power State is D3: Off

[THERMAL_TRIP]
01 = normal (A Thermal Trip is not presently detected.)
02 = thermal trip (A Thermal Trip is not presently detected.)




